[phases.setup]
cmds = [
    "curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 9.0 --install-dir /opt/dotnet",
]

[phases.build]
cmds = [
    "export PATH=/opt/dotnet:$PATH",
    "export DOTNET_ROOT=/opt/dotnet",
    "dotnet restore MOVIEBOX.csproj",
    "dotnet publish MOVIEBOX.csproj -c Release -o /app"
]

[start]
cmd = "dotnet /app/MOVIEBOX.dll --urls http://0.0.0.0:$PORT"

[build.env]
DOTNET_ROOT = "/opt/dotnet"
PATH = "/opt/dotnet:$PATH"

[build.args]
DOTNET_VERSION = "9.0"