using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieBox.Migrations
{
    /// <inheritdoc />
    public partial class AddCommentsTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 🔥 SOLO CREAR COMMENTS SI NO EXISTE
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS comments (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    username text NOT NULL,
                    text text NOT NULL,
                    rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
                    createdat timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    helpfulvotes integer NOT NULL DEFAULT 0,
                    totalvotes integer NOT NULL DEFAULT 0,
                    movieid integer NOT NULL,
                    CONSTRAINT ""PK_comments"" PRIMARY KEY (id),
                    CONSTRAINT ""FK_comments_movies_movieid"" FOREIGN KEY (movieid) REFERENCES movies (id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS ""IX_comments_movieid"" ON comments (movieid);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Eliminar solo comments
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS comments;");
        }
    }
}
